### ISSUE TITLE
Unable to set token logo

### ISSUE THREAD

**Issue by fmorency** [liftedinit/manifest-app#108]
1. Create a new token using the token factory page and set the logo URL to, e.g., 

    https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Wikimedia-logo.svg/600px-Wikimedia-logo.svg.png
1. Notice the logo is not displayed correctly.

**Comment by chalabi2** [comment]
you must add the src website  so in this instance 

upload.wikimedia.org

to the DenomImage.tsx file in `supportedDomains` and `supportedPatterns` and lastly to the next.config.js file under `domains` and `remotepatterns` we want to only keep trusted sources here, preferably ones that dont allow NSFW content since we dont have a great way to verify that ourselves.

**Comment by chalabi2** [comment]
btw i added upload.wikimedia as a source in #122

**Comment by fmorency** [comment]
Fixed by #122
